name: meshgen
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - trimesh
  - gmsh
  - mayavi
  - vtk
  - pyqt
  - tqdm
  - scikit-learn
  - matplotlib
  - pillow
  - pooch
  - scooby
  - typing-extensions
  - requests
  - pyvista
  - dash
  - plotly
  - pip
  - pip:
      - -e .
      - -e vascular_encoding_framework
