name: meshgen
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - trimesh
  - gmsh
  - mayavi
  - vtk=9.3.*
  - pyqt
  - tqdm
  - scikit-learn=1.6.*
  - matplotlib=3.9.*
  - pillow
  - pooch
  - scooby
  - typing-extensions
  - requests
  - pyvista=0.44.*
  - dash>=2.17.1,<3.0.0
  - plotly>=5.23.0,<6.0.0
  - pip
  - pip:
      - -e .
      - -e vascular_encoding_framework
